blank_issues_enabled: false
contact_links:
  - name: README
    url: https://github.com/???/ModularMachinery-Community-Edition#readme
    about: Check the README and bundled documentation before filing an issue.
